# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('alam', 'Wisata Alam'), ('bahari', 'Bahari'), ('bawah_laut', 'Bawah Laut'), ('ekowisata', 'Ekowisata'), ('petualangan', 'Petualangan'), ('menginap', 'Menginap')], max_length=20, verbose_name='Kategori')),
                ('summary', models.CharField(max_length=255, verbose_name='Ringkasan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('image_url', models.URLField(blank=True, verbose_name='URL Gambar')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objek Wisata',
                'verbose_name_plural': 'Objek Wisata',
                'ordering': ['name'],
            },
        ),
    ]
