# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('budaya', 'Budaya'), ('bahari', 'Bahari'), ('pelatihan', 'Pelatihan'), ('pemerintahan', 'Pemerintahan')], max_length=20, verbose_name='Kategori')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Ringkasan')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Acara',
                'verbose_name_plural': 'Acara & Kegiatan',
                'ordering': ['start_date'],
            },
        ),
    ]
