# Generated by Django 6.0.7 on 2026-07-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL Gambar'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.TextField(blank=True, help_text='Opsional. Tulis sebagai daftar di editor, mis. "08.00 — Pembukaan", "09.00 — Sambutan Kepala Kampung". Kosongkan jika belum tersedia.', verbose_name='Susunan Acara (Timeline)'),
        ),
    ]
