# Generated by Django 6.0.7 on 2026-07-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_event_image_url_event_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.TextField(blank=True, help_text='Opsional. Tulis sebagai daftar di editor, mis. "08.00 — Pembukaan", "09.00 — Sambutan Kepala Kampung". Kosongkan jika belum tersedia.', verbose_name='Agenda'),
        ),
    ]
