# Generated by Django 6.0.7 on 2026-07-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kegiatan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event', verbose_name='Acara')),
            ],
            options={
                'verbose_name': 'Hal yang Bisa Dilakukan',
                'verbose_name_plural': 'Hal yang Bisa Dilakukan',
                'ordering': ['order', 'id'],
            },
        ),
    ]
