[project]
name = "yongsu-desoyo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.7",
    "django-browser-reload>=1.21.0",
    "django-debug-toolbar>=7.0.0",
    "django-tailwind[cookiecutter,honcho,reload]>=4.5.0",
    "django-unfold>=0.100.0",
    "gunicorn>=26.0.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "python-decouple>=3.8",
    "whitenoise>=6.12.0",
]
