# Generated by Django 6.0.7 on 2026-07-13 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('pembangunan', 'Pembangunan'), ('ekowisata', 'Ekowisata'), ('budaya', 'Budaya'), ('kesiapsiagaan', 'Kesiapsiagaan'), ('pengumuman', 'Pengumuman')], max_length=20, verbose_name='Kategori')),
                ('summary', models.CharField(max_length=300, verbose_name='Ringkasan')),
                ('body', models.TextField(blank=True, verbose_name='Isi')),
                ('image_url', models.URLField(blank=True, verbose_name='URL Gambar')),
                ('published_at', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Terbit')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita & Pengumuman',
                'ordering': ['-published_at'],
            },
        ),
    ]
