# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
                ('value', models.PositiveIntegerField(verbose_name='Nilai')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Statistik',
                'verbose_name_plural': 'Statistik Kampung',
                'ordering': ['order', 'id'],
            },
        ),
    ]
