# Generated by Django 6.0.7 on 2026-07-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sub-judul')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Kapsi')),
                ('image_url', models.URLField(verbose_name='URL Gambar')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slide (Beranda)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('pemerintah', 'Pemerintah Kampung'), ('kaur', 'Kepala Urusan'), ('adat', 'Lembaga Adat')], default='pemerintah', max_length=20, verbose_name='Kelompok')),
                ('position', models.CharField(max_length=150, verbose_name='Jabatan / Lembaga')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nama')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Struktur Pemerintahan',
                'verbose_name_plural': 'Struktur Pemerintahan',
                'ordering': ['order', 'id'],
            },
        ),
    ]
