# Generated by Django 6.0.7 on 2026-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_set_site_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slide'},
        ),
        migrations.AddField(
            model_name='officialposition',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL Foto'),
        ),
    ]
