# Generated by Django 6.0.7 on 2026-08-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_alter_heroslide_options_officialposition_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='officialposition',
            name='image_url',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(default='', upload_to='hero/', verbose_name='Gambar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialposition',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pejabat/', verbose_name='Foto'),
        ),
    ]
