# Generated by Django 6.0.7 on 2026-08-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_remove_heroslide_image_url_and_more'),
        ('gallery', '0002_remove_photo_image_url_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Penanda teknis yang dipakai template untuk mencari banner ini -- jangan diubah.', max_length=60, unique=True, verbose_name='Kunci Halaman')),
                ('label', models.CharField(max_length=150, verbose_name='Nama Halaman')),
                ('photo', models.ForeignKey(blank=True, help_text='Dipilih dari foto yang sudah diunggah di Galeri Foto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.photo', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Banner Halaman',
                'verbose_name_plural': 'Banner Halaman',
                'ordering': ['label'],
            },
        ),
    ]
