# Generated by Django 6.0.7 on 2026-08-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_pagebanner'),
        ('gallery', '0002_remove_photo_image_url_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Penanda teknis (menentukan ikon yang tampil) -- jangan diubah.', max_length=30, unique=True, verbose_name='Kunci')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('line1', models.CharField(blank=True, max_length=200, verbose_name='Baris 1')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='Baris 2')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Kanal Kontak',
                'verbose_name_plural': 'Kanal Kontak',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FastFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('quick_facts', 'Fakta Ringkas (Tentang)'), ('boundaries', 'Batas Wilayah (Tentang)')], max_length=20, verbose_name='Kelompok')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('value', models.CharField(max_length=150, verbose_name='Nilai')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Fakta Singkat',
                'verbose_name_plural': 'Fakta Singkat',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Poin Misi',
                'verbose_name_plural': 'Poin Misi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Penanda teknis yang dipakai template untuk mencari bagian ini -- jangan diubah.', max_length=60, unique=True, verbose_name='Kunci Bagian')),
                ('page', models.CharField(choices=[('beranda', 'Beranda'), ('tentang', 'Tentang Kampung'), ('kontak', 'Kontak'), ('ppid', 'PPID')], max_length=20, verbose_name='Halaman')),
                ('label', models.CharField(help_text='Untuk memudahkan admin, tidak tampil di situs.', max_length=150, verbose_name='Nama Bagian')),
                ('eyebrow', models.CharField(blank=True, help_text='Teks kecil di atas judul, mis. "Sekilas Kampung".', max_length=100, verbose_name='Label Kecil')),
                ('heading', models.CharField(blank=True, max_length=200, verbose_name='Judul')),
                ('body', models.TextField(blank=True, verbose_name='Isi Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Teks Bagian Halaman',
                'verbose_name_plural': 'Teks Bagian Halaman',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@yongsu-desoyo.id', max_length=254, verbose_name='Email Kontak')),
                ('phone_display', models.CharField(default='0858-2446-6260', max_length=30, verbose_name='Telepon (tampilan)')),
                ('phone_e164', models.CharField(default='+6285824466260', help_text='Format internasional dengan tanda +, contoh: +6285824466260', max_length=20, verbose_name='Telepon (format internasional)')),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Penanda teknis (menentukan ikon yang tampil) -- jangan diubah.', max_length=30, unique=True, verbose_name='Kunci')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Tautan Sosial Media',
                'verbose_name_plural': 'Tautan Sosial Media',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_label', models.CharField(blank=True, help_text='Contoh: "Terletak di"', max_length=60, verbose_name='Label Lencana')),
                ('badge_value', models.CharField(blank=True, help_text='Contoh: "Kaki Cycloop · Tepi Pasifik"', max_length=100, verbose_name='Isi Lencana')),
                ('quote', models.CharField(blank=True, help_text='Hanya dipakai di bagian Sejarah Singkat.', max_length=300, verbose_name='Kutipan')),
                ('photo', models.ForeignKey(blank=True, help_text='Dipilih dari foto yang sudah diunggah di Galeri Foto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Foto Utama')),
                ('photo_secondary', models.ForeignKey(blank=True, help_text='Foto kecil yang menimpa sudut foto utama -- hanya dipakai di beranda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Foto Kedua')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='commons.pagesection', verbose_name='Bagian')),
            ],
            options={
                'verbose_name': 'Foto, Lencana & Kutipan',
                'verbose_name_plural': 'Foto, Lencana & Kutipan',
            },
        ),
    ]
