# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('image_url', models.URLField(verbose_name='URL Gambar')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Galeri Foto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
