# Generated by Django 6.0.7 on 2026-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='gallery/', verbose_name='Gambar'),
            preserve_default=False,
        ),
    ]
