# Generated by Django 6.0.7 on 2026-08-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0007_contactchannel_fastfact_missionpoint_pagesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Pertanyaan')),
                ('answer', models.TextField(verbose_name='Jawaban')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_letter', models.CharField(help_text='Contoh: "B", "S", "T", "D"', max_length=2, verbose_name='Huruf Lencana')),
                ('title', models.CharField(max_length=150, verbose_name='Judul')),
                ('description', models.CharField(max_length=300, verbose_name='Deskripsi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Klasifikasi Informasi',
                'verbose_name_plural': 'Klasifikasi Informasi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Dasar Hukum',
                'verbose_name_plural': 'Dasar Hukum',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PpidTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Tugas & Fungsi',
                'verbose_name_plural': 'Tugas & Fungsi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Syarat Permohonan',
                'verbose_name_plural': 'Syarat Permohonan',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul')),
                ('description', models.CharField(max_length=300, verbose_name='Deskripsi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Langkah Permohonan',
                'verbose_name_plural': 'Langkah Permohonan',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoClassificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Teks')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ppid.infoclassification', verbose_name='Klasifikasi')),
            ],
            options={
                'verbose_name': 'Poin Klasifikasi Informasi',
                'verbose_name_plural': 'Poin Klasifikasi Informasi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PpidRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_label', models.CharField(help_text='Contoh: "Atasan PPID", "Ketua PPID"', max_length=100, verbose_name='Peran PPID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('official', models.ForeignKey(blank=True, help_text='Dipilih dari Struktur Pemerintahan.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.officialposition', verbose_name='Dijabat oleh')),
            ],
            options={
                'verbose_name': 'Struktur Pengelola PPID',
                'verbose_name_plural': 'Struktur Pengelola PPID',
                'ordering': ['order', 'id'],
            },
        ),
    ]
