# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=300, verbose_name='Ringkasan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('image_url', models.URLField(blank=True, verbose_name='URL Gambar')),
                ('status', models.CharField(choices=[('direncanakan', 'Direncanakan'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai')], default='berjalan', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Progres (%)')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyek Pembangunan',
                'verbose_name_plural': 'Program & Proyek',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
