# Generated by Django 6.0.7 on 2026-07-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sumber Dana'),
        ),
        migrations.AddField(
            model_name='project',
            name='implementer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pelaksana'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lokasi'),
        ),
    ]
