# Generated by Django 6.0.7 on 2026-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_project_funding_source_project_implementer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='development/', verbose_name='Gambar'),
        ),
    ]
