# Generated by Django 6.0.7 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('summary', models.CharField(max_length=300, verbose_name='Ringkasan')),
                ('icon', models.CharField(choices=[('shield', 'Perisai'), ('bag', 'Tas / Noken'), ('book', 'Buku / Bahasa'), ('ritual', 'Ritual')], default='ritual', max_length=10, verbose_name='Ikon')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ditampilkan')),
            ],
            options={
                'verbose_name': 'Budaya & Tradisi',
                'verbose_name_plural': 'Budaya & Tradisi',
                'ordering': ['order', 'name'],
            },
        ),
    ]
