# Generated by Django 6.0.7 on 2026-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=150, verbose_name='UMKM / Produsen'),
        ),
    ]
