# Generated by Django 6.0.7 on 2026-07-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, verbose_name='Spesifikasi'),
        ),
    ]
